server:
  port: 8081

spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&autoReconnect=true&autoReconnectForPools=true
  jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL5Dialect
      hibernate:
        ddl-auto: update